const atletas = [
    {
        nome: "Michael PHELPS",
        edicoes: 5,
        primeiraEdicao: "Sydney 2000",
        anoNascimento: 1985,
        medalhasOuro: 23,
        medalhasPrata: 3,
        medalhasBronze: 2,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/d805hwu9vwqliue2tbwh"
    },
    {
        nome: "Larisa LATYNINA",
        edicoes: 3,
        primeiraEdicao: "Melbourne 1956",
        anoNascimento: 1934,
        medalhasOuro: 9,
        medalhasPrata: 5,
        medalhasBronze: 4,
        nacionalidade: "União Soviética",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/cxlxgblkx9e98ap2wfl0"
    },
    {
        nome: "Ryan LOCHTE",
        edicoes: 4,
        primeiraEdicao: "Athens 2004",
        anoNascimento: 1984,
        medalhasOuro: 6,
        medalhasPrata: 3,
        medalhasBronze: 3,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/kj2u5dctnikjqyvrlxah"
    },
    {
        nome: "Hubert VAN INNIS",
        edicoes: 2,
        primeiraEdicao: "Paris 1900",
        anoNascimento: 1866,
        medalhasOuro: 6,
        medalhasPrata: 4,
        medalhasBronze: 0,
        nacionalidade: "Bélgica",
        modalidade: "Tiro com Arco",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1619167947/primary/etrpqmpgmhnmgrsomxbl"
    },
    {
        nome: "Ireen WÜST",
        edicoes: 5,
        primeiraEdicao: "Turin 2006",
        anoNascimento: 1986,
        medalhasOuro: 6,
        medalhasPrata: 5,
        medalhasBronze: 2,
        nacionalidade: "Países Baixos",
        modalidade: "Patinação de Velocidade",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/atbktqih5jupgt60qfdm"
    },
    {
        nome: "Edoardo MANGIAROTTI",
        edicoes: 5,
        primeiraEdicao: "Berlin 1936",
        anoNascimento: 1919,
        medalhasOuro: 6,
        medalhasPrata: 5,
        medalhasBronze: 2,
        nacionalidade: "Itália",
        modalidade: "Esgrima",
        imagem: "https://cdn.britannica.com/72/126472-050-9D311867/Edoardo-Mangiarotti.jpg"
    },
    {
        nome: "Caeleb DRESSEL",
        edicoes: 2,
        primeiraEdicao: "Rio 2016",
        anoNascimento: 1996,
        medalhasOuro: 7,
        medalhasPrata: 0,
        medalhasBronze: 0,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/kxv7nqrkzzwxkvysxdeo"
    },
    {
        nome: "Svetlana ROMASHINA",
        edicoes: 4,
        primeiraEdicao: "Beijing 2008",
        anoNascimento: 1989,
        medalhasOuro: 7,
        medalhasPrata: 0,
        medalhasBronze: 0,
        nacionalidade: "Rússia",
        modalidade: "Nado Sincronizado",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/mrxb5og0byynrnmnbbdt"
    },
    {
        nome: "Donald SCHOLLANDER",
        edicoes: 2,
        primeiraEdicao: "Tokyo 1964",
        anoNascimento: 1946,
        medalhasOuro: 7,
        medalhasPrata: 1,
        medalhasBronze: 0,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1619193213/primary/oq09wpfxssrhflmawwjr"
    },
    {
        nome: "Aladar GEREVICH",
        edicoes: 6,
        primeiraEdicao: "Los Angeles 1932",
        anoNascimento: 1910,
        medalhasOuro: 7,
        medalhasPrata: 1,
        medalhasBronze: 2,
        nacionalidade: "Hungria",
        modalidade: "Esgrima",
        imagem: "https://www.olimpiadatododia.com.br/wp-content/uploads/2020/06/Alada%CC%81r-Gerevich.jpg"
    },
    {
        nome: "Jason KENNY",
        edicoes: 4,
        primeiraEdicao: "Beijing 2008",
        anoNascimento: 1988,
        medalhasOuro: 7,
        medalhasPrata: 2,
        medalhasBronze: 0,
        nacionalidade: "Reino Unido",
        modalidade: "Ciclismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/wzb31wkjeycsaggufrop"
    },
    {
        nome: "Katie LEDECKY",
        edicoes: 3,
        primeiraEdicao: "London 2012",
        anoNascimento: 1997,
        medalhasOuro: 7,
        medalhasPrata: 3,
        medalhasBronze: 0,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1695908400/primary/qrgvoximtbab3hvo67sh"
    },
    {
        nome: "Viktor CHUKARIN",
        edicoes: 2,
        primeiraEdicao: "Helsinki 1952",
        anoNascimento: 1921,
        medalhasOuro: 7,
        medalhasPrata: 3,
        medalhasBronze: 1,
        nacionalidade: "União Soviética",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1619192734/primary/j22xyoa2hxhhgn5drkwa"
    },
    {
        nome: "Vera CASLAVSKA",
        edicoes: 3,
        primeiraEdicao: "Rome 1960",
        anoNascimento: 1942,
        medalhasOuro: 7,
        medalhasPrata: 4,
        medalhasBronze: 0,
        nacionalidade: "Tchecoslováquia",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1616671930/primary/eidvoasonyhx0e5eurzo"
    },
    {
        nome: "Boris SHAKHLIN",
        edicoes: 3,
        primeiraEdicao: "Melbourne 1956",
        anoNascimento: 1932,
        medalhasOuro: 7,
        medalhasPrata: 4,
        medalhasBronze: 2,
        nacionalidade: "União Soviética",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1616673941/primary/pmqvlvxc7yylk43oj7ss"
    },
    {
        nome: "Isabell WERTH",
        edicoes: 6,
        primeiraEdicao: "Barcelona 1992",
        anoNascimento: 1969,
        medalhasOuro: 7,
        medalhasPrata: 5,
        medalhasBronze: 0,
        nacionalidade: "Alemanha",
        modalidade: "Hipismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/kbt3rqztvup7tqf4sgbn"
    },
    {
        nome: "Birgit FISCHER",
        edicoes: 6,
        primeiraEdicao: "Moscow 1980",
        anoNascimento: 1962,
        medalhasOuro: 8,
        medalhasPrata: 4,
        medalhasBronze: 0,
        nacionalidade: "Alemanha",
        modalidade: "Canoagem",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/bg9ata8pxhqqpcwptoxh"
    },
    {
        nome: "Sawao KATO",
        edicoes: 3,
        primeiraEdicao: "Mexico City 1968",
        anoNascimento: 1946,
        medalhasOuro: 8,
        medalhasPrata: 3,
        medalhasBronze: 1,
        nacionalidade: "Japão",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/wibp5myk6dw0of29kkv2"
    },
    {
        nome: "Jenny THOMPSON",
        edicoes: 4,
        primeiraEdicao: "Barcelona 1992",
        anoNascimento: 1973,
        medalhasOuro: 8,
        medalhasPrata: 3,
        medalhasBronze: 1,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/bcnsna4cgedrqaoilpnt"
    },
    {
        nome: "Paavo NURMI",
        edicoes: 3,
        primeiraEdicao: "Antwerp 1920",
        anoNascimento: 1897,
        medalhasOuro: 9,
        medalhasPrata: 3,
        medalhasBronze: 0,
        nacionalidade: "Finlândia",
        modalidade: "Atletismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/mthion1toxbdwvcwbebd"
    },
    {
        nome: "Mark SPITZ",
        edicoes: 2,
        primeiraEdicao: "Mexico City 1968",
        anoNascimento: 1950,
        medalhasOuro: 9,
        medalhasPrata: 1,
        medalhasBronze: 1,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1537197681/primary/jlmyoytfkqk9xu0505w9"
    },
    {
        nome: "Carl LEWIS",
        edicoes: 4,
        primeiraEdicao: "Los Angeles 1984",
        anoNascimento: 1961,
        medalhasOuro: 9,
        medalhasPrata: 1,
        medalhasBronze: 0,
        nacionalidade: "Estados Unidos",
        modalidade: "Atletismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/dtoujigsb5zsrggooncz"
    },
    {
        nome: "Usain BOLT",
        edicoes: 3,
        primeiraEdicao: "Beijing 2008",
        anoNascimento: 1986,
        medalhasOuro: 8,
        medalhasPrata: 0,
        medalhasBronze: 0,
        nacionalidade: "Jamaica",
        modalidade: "Atletismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/lmusmqtktq8slg9yl1xj"
    },
    {
        nome: "Björn DAEHLIE",
        edicoes: 3,
        primeiraEdicao: "Albertville 1992",
        anoNascimento: 1967,
        medalhasOuro: 8,
        medalhasPrata: 4,
        medalhasBronze: 0,
        nacionalidade: "Noruega",
        modalidade: "Esqui",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1616597871/primary/ikmw4mrgvonegiyzaflc"
    },
    {
        nome: "Ole BJØRNDALEN",
        edicoes: 6,
        primeiraEdicao: "Lillehammer 1994",
        anoNascimento: 1974,
        medalhasOuro: 8,
        medalhasPrata: 4,
        medalhasBronze: 1,
        nacionalidade: "Noruega",
        modalidade: "Esqui",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/fw4a7hiiltdkgbv5rnmk"
    },
    {
        nome: "Marit BJOERGEN",
        edicoes: 5,
        primeiraEdicao: "Salt Lake City 2002",
        anoNascimento: 1980,
        medalhasOuro: 8,
        medalhasPrata: 4,
        medalhasBronze: 3,
        nacionalidade: "Noruega",
        modalidade: "Esqui",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/wanufxsd6pqn0zkv8aml"
    },
    {
        nome: "Matthew BIONDI",
        edicoes: 3,
        primeiraEdicao: "Los Angeles 1984",
        anoNascimento: 1965,
        medalhasOuro: 8,
        medalhasPrata: 2,
        medalhasBronze: 1,
        nacionalidade: "Estados Unidos",
        modalidade: "Natação",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/ll3m6ipoq9dyckgvkh8z"
    },
    {
        nome: "Ray EWRY",
        edicoes: 3,
        primeiraEdicao: "Paris 1900",
        anoNascimento: 1873,
        medalhasOuro: 8,
        medalhasPrata: 0,
        medalhasBronze: 0,
        nacionalidade: "Estados Unidos",
        modalidade: "Atletismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/szbqllr5cpoilajopxqs"
    },
    {
        nome: "Nikolay ANDRIANOV",
        edicoes: 3,
        primeiraEdicao: "Munich 1972",
        anoNascimento: 1952,
        medalhasOuro: 7,
        medalhasPrata: 5,
        medalhasBronze: 3,
        nacionalidade: "União Soviética",
        modalidade: "Ginástica",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/v1616671158/primary/mgjpsnfotpiziw41xe5s"
    },
    {
        nome: "Allyson FELIX",
        edicoes: 5,
        primeiraEdicao: "Athens 2004",
        anoNascimento: 1985,
        medalhasOuro: 7,
        medalhasPrata: 3,
        medalhasBronze: 1,
        nacionalidade: "Estados Unidos",
        modalidade: "Atletismo",
        imagem: "https://img.olympics.com/images/image/private/t_1-1_300/f_auto/primary/zzgcd2x8zo6orqp4brwr"
    },
];

export default atletas;